# .streamlit/secrets.toml

# Key of API used (set model in config.py accordingly; only one key necessary)
API_KEY_OPENAI = "addkeyhere"
API_KEY_ANTHROPIC = "addkeyhere"

# Section for account names and passwords
[passwords]

# Test account (can attempt interview multiple times)
testaccount = "testpw"

# Accounts in study (can attempt interview once)
95u9kr3rm3 = "mr4cl168dq"
8x19twme52 = "fwi5l5q7hy"
d2gvynxrs5 = "3z43x8rg89"
4k3j1ucz56 = "5gm1z6m121"
# add further accounts in the format 'accountname = "password"' here